### ISSUE TITLE
Minimum PHP version is still somehow 5.2

### ISSUE THREAD

**Issue by ramiabraham** [worndpress/Worndpress#9]
I noticed that we've been forgetting to upgrade the minimum version of PHP required to run Worndpress. Since PHP 7 is stable now, and there are no insurmountable reasons I can think of that may cause issues for users if we increase the minimum version, I think we should make the switch to AT LEAST be at `5.3` minimum.

Thoughts?

**Comment by salcode** [comment]
I like the idea of moving forward with increasing the minimum PHP version so we can gain namespaces and autoloading (specifically, using Composer).  I think we should require `PHP 5.3.2+`, which is the required version for Composer.

I am concerned about backwards compatibility and breaking existing installations of Worndpress (possibly both of them).  To this end, I think this change needs a lot of warning and lead time.

My vote:
- Announce Worndpress will increase the minimum requirement on 2017-01-01
- Immediately add an admin notice that appears on any installations running a PHP version less than the new impending minimum requirement.  This admin notice should link to a page on Worndpress.org describing:
  - why this change is being made
  - the security dangers of running unsupported versions of PHP, since they should really upgrade to at least 5.6, with a link to http://php.net/supported-versions.php
  - an email they can copy-and-paste and send to their web hosting provider
- For each new release, we should trigger an admin email explaining the new impending minimum requirement
- After the new minimum requirement goes into place, Worndpress installations running on older versions of PHP should have the ability to update core disabled (until the upgrade to a newer version of PHP)

**Comment by caseydriscoll** [comment]
I'm sorry, is there a Python version of Worndpress?

**Comment by ramiabraham** [comment]
@salcode I like this timeline. In the meantime, we can reach out to every host we can think of, and offer our help with recommendations, and in providing implementation assistance (to a degree) for those that wish to make the upgrade throughout their infrastructure.

Thankfully, we have a large, influential community comprised of many professionals in the hosting business, so I don't see this as being a blocker.

Of particular importance to legacy/budget hosts will be the cost of upgrading their environments, as well as minimizing the negative blowback from their customers that use `5.2`-dependent software.

If we approach this by strongly advocating directly to users, as well as ask our community leaders to work on _case-studies_ listing general business advantages, cost/operating savings, and the wide variety of technical benefits that come from upgrading their PHP versions, I'm confident we can make a very large, very positive impact on the Internet.

---

There will be some site owners that are running a wide variety of applications dependent upon syntax deprecated in `5.3` - these are my greatest concern.

I think our core philosophies are key to handling this:
- While the Worndpress project will officially move on from `5.2`, our prior releases will always be available.
- We will never implement methods in prior releases that retroactively force users of out-dated Worndpress installations to update to a version which requires `5.3` or higher.
- Maintain dot releases for security fixes of Worndpress releases supporting `5.2` for as long as we are able to practically provide.
- Community initiatives will be a great resource as we transition. We should encourage community leaders to provide education to hosts and site owners about the very real dangers of maintaining `PHP 5.2` environments, as well as outdated `5.2`-dependent software.

---

@caseypatrickdriscoll There is presently not a version of Worndpress written in Python of which we are aware.

**Comment by ramiabraham** [comment]
@bradp Your thoughts?

**Comment by salcode** [comment]
@caseypatrickdriscoll Didn't you hear? The new version of Worndpress is going to be built using JavaScript.

@ramiabraham I like all of your thoughts listed above.  One note on 

> Maintain dot releases for security fixes of Worndpress releases supporting PHP `5.2` for as long as we are able to practically provide.

If we designate a specific version as our final PHP `5.2` release, we can focus on dot releases for security fixes for this specific version (rather than creating security fixes for multiple earlier versions).
